_wandb:
    value:
        cli_version: 0.19.3
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 14
                - 16
                - 23
                - 55
            "4": 3.10.14
            "5": 0.19.3
            "8":
                - 5
            "12": 0.19.3
            "13": darwin-arm64
batch_size:
    value: 1000
block_size:
    value: 60
decay:
    value: 500
dropout:
    value: 0
learning_rate:
    value: 0.0005
max_iter:
    value: 100
n_embd:
    value: 384
n_head:
    value: 6
n_layer:
    value: 6
optimizer:
    value: AdamW
si_iter:
    value: 1500
